services:
  # ─── Nginx (リバースプロキシ) ─────────────────────
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app_net

  # ─── Frontend (Next.js 開発サーバー) ────────────────
  frontend:
    container_name: ${COMPOSE_PROJECT_NAME}-frontend
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
      args:
        # ビルド時に .env の URL を注入
        NEXT_PUBLIC_API_BASE_URL: "${NEXT_PUBLIC_API_BASE_URL}"
    ports:
      - "${FRONTEND_PORT}:3000"
    working_dir: /app/apps/frontend
    volumes:
      # ホストコードをマウントしてホットリロード
      - ../apps/frontend:/app/apps/frontend:delegated
    networks:
      - app_net

  # ─── Backend (FastAPI / uvicorn) ────────────────────
  backend:
    container_name: ${COMPOSE_PROJECT_NAME}-backend
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    ports:
      - "${BACKEND_PORT}:8000"
    working_dir: /app/apps/backend
    volumes:
      - ../apps/backend:/app/apps/backend:delegated
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
