services:
  frontend:
    build:
      context: ../
      dockerfile: ./docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:8000/api
    working_dir: /app/apps/frontend
    volumes:
      - ../apps/frontend:/app/apps/frontend
    depends_on:
      - backend

  backend:
    build:
      context: ../
      dockerfile: ./docker/backend.Dockerfile
    ports:
      - "8000:8000"
    working_dir: /app/apps/backend
    volumes:
      - ../apps/backend:/app/apps/backend
